project:
  type: website

website:
  title: "Caesar0984"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - text: Blog
        menu:
          - href: posts/first_post.qmd
            text: First Blog Post
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

# GitHub Pages configuration
output-dir: docs
